In [ ]:
from sklearn import datasets
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import decomposition
from sklearn.naive_bayes import GaussianNB
import numpy as np
from sklearn import metrics
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score
%matplotlib inline

faces = datasets.fetch_olivetti_faces()
faces.data.shape

fig = plt.figure(figsize=(10, 8))
# for i in range(10):
#   ax = fig.add_subplot(3, 5, i + 1, xticks=[], yticks=[])
#   ax.imshow(faces.images[i], cmap=plt.cm.bone)

trainF, testF, trainL, testL = train_test_split(faces.data, faces.target, random_state=0, test_size=0.1)

pca = decomposition.PCA(n_components=150)
pca.fit(trainF)

# plt.imshow(pca.mean_.reshape(faces.images[0].shape), cmap=plt.cm.bone)

model = GaussianNB()
model.fit(trainF, trainL)

predicted = model.predict(testF)
print('Accuracy {}'.format(accuracy_score(testL, predicted)))
print('Precision {}'.format(precision_score(testL, predicted, average='weighted')))
print('Recall {}'.format(recall_score(testL, predicted, average='weighted')))

trainPCA = pca.transform(trainF)
testPCA = pca.transform(testF)

model2 = GaussianNB()
model2.fit(trainPCA, trainL)
predicted2 = model2.predict(testPCA)

print('\nAccuracy {}'.format(accuracy_score(testL, predicted2)))
print('Precision {}'.format(precision_score(testL, predicted2, average='weighted')))
print('Recall {}'.format(recall_score(testL, predicted2, average='weighted')))

# print(metrics.classification_report(testL, predicted2))
# print(metrics.confusion_matrix(testL, predicted2))

Accuracy 0.8
Precision 0.8208333333333332
Recall 0.8

Accuracy 0.85
Precision 0.9708333333333332
Recall 0.85


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


<Figure size 720x576 with 0 Axes>

In [ ]:
from sklearn import datasets
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import decomposition
from sklearn.naive_bayes import GaussianNB
import numpy as np
from sklearn import metrics
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score
%matplotlib inline
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

faces = datasets.fetch_olivetti_faces()
faces.data.shape

fig = plt.figure(figsize=(10, 8))

trainF, testF, trainL, testL = train_test_split(faces.data, faces.target, random_state=0, test_size=0.2)

model = DecisionTreeClassifier(max_leaf_nodes=9000)
model.fit(trainF, trainL)

plt.figure(figsize=(30,10))
# a = tree.plot_tree(model, feature_names=trainF, class_names=trainL, rounded = True, filled = True, fontsize=14)
plt.show()

output = model.predict(testF)

print('Accuracy {}'.format(accuracy_score(testL, output)))
print('Precision {}'.format(precision_score(testL, output, average='weighted')))
print('Recall {}'.format(recall_score(testL, output, average='weighted')))

<Figure size 720x576 with 0 Axes>

<Figure size 2160x720 with 0 Axes>

Accuracy 0.5875
Precision 0.6485416666666668
Recall 0.5875


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn import datasets
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import decomposition
from sklearn.naive_bayes import GaussianNB
import numpy as np
from sklearn import metrics
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score
%matplotlib inline
from sklearn.svm import LinearSVC

faces = datasets.fetch_olivetti_faces()
faces.data.shape

fig = plt.figure(figsize=(10, 8))

trainF, testF, trainL, testL = train_test_split(faces.data, faces.target, random_state=0, test_size=0.2)

model = LinearSVC()
model.fit(trainF, trainL)

plt.figure(figsize=(30,10))
# a = tree.plot_tree(model, feature_names=trainF, class_names=trainL, rounded = True, filled = True, fontsize=14)
plt.show()

output = model.predict(testF)

print('Accuracy {}'.format(accuracy_score(testL, output)))
print('Precision {}'.format(precision_score(testL, output, average='weighted')))
print('Recall {}'.format(recall_score(testL, output, average='weighted')))

/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


<Figure size 720x576 with 0 Axes>

<Figure size 2160x720 with 0 Axes>

Accuracy 0.975
Precision 0.96875
Recall 0.975


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn import datasets
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import decomposition
from sklearn.naive_bayes import GaussianNB
import numpy as np
from sklearn import metrics
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score
%matplotlib inline

faces = datasets.load_iris()
faces.data.shape

fig = plt.figure(figsize=(10, 8))
# for i in range(10):
#   ax = fig.add_subplot(3, 5, i + 1, xticks=[], yticks=[])
#   ax.imshow(faces.images[i], cmap=plt.cm.bone)

trainF, testF, trainL, testL = train_test_split(faces.data, faces.target, random_state=0, test_size=0.1)

pca = decomposition.PCA(n_components=4)
pca.fit(trainF)

# plt.imshow(pca.mean_.reshape(faces.images[0].shape), cmap=plt.cm.bone)

model = GaussianNB()
model.fit(trainF, trainL)

predicted = model.predict(testF)
print('Accuracy {}'.format(accuracy_score(testL, predicted)))
print('Precision {}'.format(precision_score(testL, predicted, average='weighted')))
print('Recall {}'.format(recall_score(testL, predicted, average='weighted')))

print(metrics.classification_report(testL, predicted))
print(metrics.confusion_matrix(testL, predicted))

trainPCA = pca.transform(trainF)
testPCA = pca.transform(testF)

model2 = GaussianNB()
model2.fit(trainPCA, trainL)
predicted2 = model2.predict(testPCA)

print('\nAccuracy {}'.format(accuracy_score(testL, predicted2)))
print('Precision {}'.format(precision_score(testL, predicted2, average='weighted')))
print('Recall {}'.format(recall_score(testL, predicted2, average='weighted')))

print(metrics.classification_report(testL, predicted2))
print(metrics.confusion_matrix(testL, predicted2))

Accuracy 0.9333333333333333
Precision 0.9407407407407408
Recall 0.9333333333333333
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       0.89      1.00      0.94         8
           2       1.00      0.75      0.86         4

    accuracy                           0.93        15
   macro avg       0.96      0.92      0.93        15
weighted avg       0.94      0.93      0.93        15

[[3 0 0]
 [0 8 0]
 [0 1 3]]

Accuracy 1.0
Precision 1.0
Recall 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         8
           2       1.00      1.00      1.00         4

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

[[3 0 0]
 [0 8 0]
 [0 0 4]]


<Figure size 720x576 with 0 Axes>